# Generated by Django 6.0.6 on 2026-06-17 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_following_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='core.Follow', through_fields=('follower', 'following'), to=settings.AUTH_USER_MODEL),
        ),
    ]
