# Generated by Django 6.1 on 2026-09-03 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PLAYER', 'Player'), ('COACH', 'Coach'), ('CLUB', 'Club'), ('ASSOCIATION', 'Association'), ('SPONSOR', 'Sponsor'), ('SCOUT', 'Scout')], default='PLAYER', max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
